### PR TITLE
sagemath-giac

### PR DESCRIPTION
**Pull request by mkoeppe**
Add a distribution **sagemath-giac**

Split out from https://github.com/sagemath/sage/pull/35095, as requested by @orlitzky in https://github.com/sagemath/sage/pull/38712#issuecomment-2408173064

### CODE REVIEW

**Comment by orlitzky** [comment]
Was this doable without the expanded sagemath-categories (would it work with the existing upstream sagemath-categories)?

**Comment by mkoeppe** [comment]
> would it work with the existing upstream sagemath-categories

No. 
- `src/sage/libs/giac/giac.pyx` cimports from `sage.rings.integer` and `sage.rings.rational`, which were added in #10

**Comment by orlitzky** [comment]
Ok, thanks. Is it fungible by changing the deps to sagemath_standard rather than sagemath_setup, sagemath_categories, sagemath_sagemath_environment, etc? I'm not expecting that other PR to get merged upstream any time soon.

**Comment by mkoeppe** [comment]
Of course, if you make it depend on everything, it can build.

**Pull request merged**
