### PR TITLE
Use the faster libgiac interface for "giac" integration by @orlitzky

### PR DESCRIPTION
**Pull request by mkoeppe**
Same as https://github.com/sagemath/sage/pull/38686 by @orlitzky

### CODE REVIEW

**Comment by orlitzky** [comment]
I've been meaning to go back to this. It bothers me that I don't know what's wrong with `Inf`, but my old PC is gone and the new one can't run giac so it's waiting for me to want to build sage on my laptop.

**Comment by mkoeppe** [comment]
if you are on a manylinux x86_64 platform, you can get a working giac with the passagemath-giac wheels from https://github.com/passagemath/passagemath/actions/runs/11639770576 (not uploaded to PyPI because > 100 MB for some reason)

**Comment by orlitzky** [comment]
This would be on riscv :(

**Comment by mkoeppe** [comment]
Looks like building wheels for that platform is not popular; does not look like https://github.com/pypa/cibuildwheel has support for it

**Comment by mkoeppe** [comment]
For now, I've only done
- #275

**Pull request closed without merging**
